### PR TITLE
Feature/popover auto positioning

### PR DESCRIPTION
**Pull request by dsharrison**
Implements #21 by adding a new 'auto' prefix to the positioning on popovers.

See a [demo](https://youtu.be/X-8zAxK2neU).

This has been tested with LockerService enabled. The only "hack" involved is including a hardcoded value for the global navigation header height to allow 'auto top' positioned popovers to account for the header taking up part of the viewport.

### CODE REVIEW

**Comment by dsharrison** [comment]
Looks like I had updated my testing branch from your master which is showing a bunch of extra commits in this PR. If you are not planning on making that update on your side let me know and I'll reset the state of my /testing branch to make this PR only pull in the popover changes.

**Comment by kevinberonilla** [comment]
Thanks for reopening this! Strange that all those commits are sticking out. Ever since we implemented Salesforce DX into the development workflow, we've been using the `testing` branch less for actual testing (we started testing directly in branches via scratch orgs, and again in staging before we deploy to this repo).

Before we merge this in, we'll diligently ensure nothing gets written over. If anything, we might have to do manual implementation. We'll keep you updated.

**Comment by dsharrison** [comment]
Oh gotcha, we have not started working with DX yet (can't wait since it looks like it really moves SFDC development up to a modern workflow). If you need to cherry-pick changes for this one they are all in commit 31880247fb3fbefda42323673ef46aa83832d82a.

**Comment by kevinberonilla** [comment]
We cherry-picked the commit into the `testing` branch just now. Consider this PR merged.

**Pull request closed without merging**
