### PR TITLE
Add a progress indicator component (#17)

### PR DESCRIPTION
**Pull request by dsharrison**
Add a progress indicator component for #17. The structure of this component is modeled on the strike wizard component but uses the [progress indicator lightning design system component](https://lightningdesignsystem.com/components/progress-indicator/#content). A short demo of the component can be seen [here](https://www.youtube.com/watch?v=Bv1icPtr1Sk).

This component does not currently broadcast an event to the parent component but the parent can instead bind to the `v.currentItemIndex` attribute to be notified when the step is changed.

This request also makes a change to the tooltip component to move the hit detection events from `mouseover` and `mouseout` to `mouseenter` and `mouseleave` to allow for the hit detection to occur on child elements.

### CODE REVIEW

**Comment by dsharrison** [comment]
I thought this might be made irrelevant with the `lightning:path` component added in Winter 18, but that component only supports a path/progress indicator driven by a picklist/path metadata setup. Our use case requires custom progress that isn't driven by a field on the record so I think this is still relevant.

**Comment by dsharrison** [comment]
Actually, I think I was looking at the wrong component. This might be completely redundant with `lightning:progressIndicator` (not `lightning:path`). If you think so feel free to just close this PR.

**Comment by dsharrison** [comment]
I have been playing around with the new `lightning:progressIndicator` and don't think that my PR here offers anything that standard component doesn't so I am closing this.

**Comment by georgekenessey** [comment]
Thanks @dsharrison nonetheless we appreciate your support of the Strike project.

**Comment by dsharrison** [comment]
@georgekenessey No problem, you guy have saved us countless hours of development time filling in the gaps that Salesforce is still taking their sweet time on.

**Comment by georgekenessey** [comment]
@dsharrison thanks for the props. We are all in the same boat, we need to ship stuff and need these components to make it happen. It's been fun sharing what we have done with everyone and getting all the awesome feedback and info about bugs. It helps us all.

**Pull request closed without merging**
