### PR TITLE
Add Deploy To Org button (incl. required structure changes)

### PR DESCRIPTION
**Pull request by up2go-rsoesemann**
This PR is supposed to fix https://github.com/appiphony/Strike-Components/issues/129.

To make a Deploy to Org button work in your README I had to:

1. Move metadata folders into a `src` folder
2. Generate and add a `package.xml` 
3. Add the Deploy button to `README.md`

### CODE REVIEW

**Comment by up2go-rsoesemann** [comment]
@daneowens3 any objections to this?

**Comment by kevinberonilla** [comment]
Seems like a good idea to me if there is demand for it. Internally, we've shied away from mass deployments of the entire Strike component library since it makes an org 'dirty' with unused components. This seems like an easy addition to the next release, but my initial concern is if/how the changes will conflict with our CLI. We'll take a look!

**Comment by mikeblazek** [comment]
@kevinberonilla we need to review this use case before pulling it in. Lets talk about this internally.

**Comment by up2go-rsoesemann** [comment]
Any updates here?

**Comment by mikeblazek** [comment]
@up2go-rsoesemann after reviewing internally we have decided that this does not make sense for the project as whole at this point in time.  Strike-CLI allows for people to pull components into their org and we want to keep that as our preferred method.  Combine that with the fact that most use cases people do not want the entire strike suite but instead only one or two components. 

Thank you for the pull request, we value contributions from the community.

**Pull request closed without merging**
