### PR TITLE
Ability to easily pull Strike-Components using CLI command

### PR DESCRIPTION
**Pull request by wadewegner**

### CODE REVIEW

**Comment by wadewegner** [comment]
To try this out, use this plugin: https://github.com/wadewegner/sfdx-oss-plugin

**Comment by cdcarter** [comment]
Oh @wadewegner you beautiful human.

**Comment by mikeblazek** [comment]
@wadewegner this is great.  I like the sfdx-oss-plugin.  My only question to you is there a way that we can not have to specify each and every file in the manifest.  It would easier if we just specified the folders that that should be pulled and all files in those folders get pulled over.

**Comment by wadewegner** [comment]
Yeah, that's something I want to do. I haven't figured out how to get a listing of files / folders via Github, but when I do I'll update the pull request.

**Comment by wadewegner** [comment]
Okay! I've updated my code to use folders. Take a look. Thanks!

**Pull request merged**
